# Unique name for this workflow
name: PR Validation delta (sandbox) image

# Controls when the action will run. 
on:
  push:
    branches: [script]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ecorsinisf/sfdx-cli-gitaction

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'instal sfdx git delta pluging'
        run: 'echo y | sfdx plugins:install sfdx-git-delta'
      
      # Checkout the code in the pull request
      - name: Checkout
        uses: actions/checkout@v2

      # Store secret for dev hub
      # org_auth_url parameter can be obtained by reading the "Sfdx Auth Url" returned by: sfdx force:org:display --verbose
      - name: 'Populate auth file with CI_SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.CI_SFDX_URL}} > ./CI_SFDX_URL.txt'

        # Authenticate
      - name: 'Authenticate'
        run: 'sfdx force:auth:sfdxurl:store -f ./CI_SFDX_URL.txt -a CI -d'
      
      - name: 'generate_delta_packages'
        run: |
         git fetch origin "+refs/heads/*:refs/remotes/origin/*"
         export LAST_DEPLOYED_COMMIT=$(git show-ref -s master)
         sfdx sgd:source:delta -a 51 -t HEAD -f $LAST_DEPLOYED_COMMIT -r . -o . -i manifest/mdapi/.sgdignore
         echo "--- package.xml generated with added and modified metadata since $LAST_DEPLOYED_COMMIT ---"
         cat package/package.xml
         echo
         echo "--- destructiveChanges.xml generated with deleted metadata since $LAST_DEPLOYED_COMMIT ---"
         cat destructiveChanges/destructiveChanges.xml
         echo

      - name: 'check-only'
        run : |
          echo "Check-Only"
          sfdx force:source:deploy -c -u CI -x package/package.xml -l RunLocalTests

  qauk-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the code in the pull request
      - name: Checkout
        uses: actions/checkout@v2

      # Store secret for dev hub
      # org_auth_url parameter can be obtained by reading the "Sfdx Auth Url" returned by: sfdx force:org:display --verbose
      - name: 'Populate auth file with QAUK_SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.QAUK_SFDX_URL}} > ./QAUK_SFDX_URL.txt'

        # Authenticate
      - name: 'Authenticate'
        run: 'sfdx force:auth:sfdxurl:store -f ./QAUK_SFDX_URL.txt -a SIT -d'

      - name: 'generate_delta_packages'
        run: |
         git fetch origin "+refs/heads/*:refs/remotes/origin/*"
         export LAST_DEPLOYED_COMMIT=$(git show-ref -s master)
         sfdx sgd:source:delta -a 51 -t HEAD -f $LAST_DEPLOYED_COMMIT -r . -o . -i manifest/mdapi/.sgdignore
         echo "--- package.xml generated with added and modified metadata since $LAST_DEPLOYED_COMMIT ---"
         cat package/package.xml
         echo
         echo "--- destructiveChanges.xml generated with deleted metadata since $LAST_DEPLOYED_COMMIT ---"
         cat destructiveChanges/destructiveChanges.xml
         echo

      - name: 'check-only'
        run : |
         echo "Full Check-Only"
         sfdx force:source:deploy -c -u QAUK -x package/package.xml -l RunLocalTests
